### ISSUE TITLE
QA: Forbedre testdekning

### ISSUE THREAD

**Issue by nav-svejk** [navikt/melosys-eessi#16]
Testdekningen (i følge EclEmma) står per 29.03.19 på 35.4%. Det er mange meninger, og liten grad av konsensus i NAV, om hvor høy dekning man bør ha, men i min erfaring tenker jeg at ett sted mellom 80-90% er godt nok. Da er trivialiteter som JavaBeans og Spring-konfigurasjon uten interessant oppførsel utelatt fra testing. Sjekk med @frans-a hvilket nivå dere skal ligge på i Melosys.

Dersom testdekningen forblir lav etter forbedring av ikke-triviell kode, vær oppmerksom på at det som regel betyr at dere har død kode (POJO-er som ikke er i bruk o.l.).

**Comment by AStrand94** [comment]
Testdekning som står igjen nå kommer i hovedsak grunnet POJO-er og Config-klasser, da datamodellene for SED-er er ganske omfattende. Lukker da denne
